stages:
  - build
  - push

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
      alias: docker
  script:
    - docker build -t cloudproxy .
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""


push_image:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker tag cloudproxy 192.168.68.11:32768/cloudproxy
    - docker push 192.168.68.11:32768/cloudproxy